#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Wed Mar 10 18:03:58 2021
#

import wx


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Dolgozók heti órái", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_1.Add(label_1, 0, wx.ALL | wx.EXPAND, 6)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Azonosító", style=wx.ALIGN_RIGHT)
        sizer_2.Add(label_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.azonosito_text = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_2.Add(self.azonosito_text, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Órabér", style=wx.ALIGN_RIGHT)
        sizer_3.Add(label_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.oraber_text = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_3.Add(self.oraber_text, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Heti ledolgozott órák", style=wx.ALIGN_RIGHT)
        sizer_4.Add(label_4, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.orak_text = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_4.Add(self.orak_text, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.mentes_button = wx.Button(self.panel_1, wx.ID_ANY, u"Mentés")
        sizer_1.Add(self.mentes_button, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 6)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Kereset", style=wx.ALIGN_RIGHT)
        sizer_5.Add(label_5, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.kereset_text = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_5.Add(self.kereset_text, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.click_mentes_button, self.mentes_button)
        # end wxGlade
        self.beolvas_berek()

    def click_mentes_button(self, event):  # wxGlade: MyFrame.<event_handler>
        azonosito = self.azonosito_text.GetValue()
        oraber = float(self.oraber_text.GetValue())
        orak = float(self.orak_text.GetValue())
        
        if orak > 40:
            kulonbseg = orak-40
            plusz = (kulonbseg * oraber)/2
            kereset = oraber * orak
            kereset = kereset + plusz
        else:
            kereset = oraber * orak
        
        self.kereset_text.SetValue(str(kereset))
        self.ber_mentes(azonosito, str(oraber), str(orak))
        event.Skip()

    def ber_mentes(self, azonosito, oraber, orak):
        line = azonosito + ":" + oraber + ":" + orak + "\n"
        fp = open('munkak.txt', 'a')
        fp.write(line)
        fp.close()
        print('A kiírás véget ért')

    def beolvas_berek(self):
        fp = open('munkak.txt', 'r')
        lines = fp.readlines()
        # ~ fp.close()
        # ~ (az, oraber, orak) =lines[0].split(':')
        
        # ~ max = int(az)
        # ~ for line in lines:
            # ~ line = line.rstrip()
            # ~ (azStr, oraber, orak) = line.split(':')
            # ~ az = int(azStr)
            # ~ if az > max:
                # ~ max = az
        # ~ ujAzonosito = max + 1
        # ~ self.azonosito_text.SetValue(str(ujAzonosito))

# end of class MainFrame
      
class BeresApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = BeresApp(0)
    app.MainLoop()
