#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.0a9 on Wed Dec 16 20:10:58 2020
#

import wx
import math

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 313))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Kúptérfogat")
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Sugár")
        sizer_1.Add(label_2, 0, wx.ALL, 5)

        self.sugarText = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_1.Add(self.sugarText, 0, wx.ALL | wx.EXPAND, 5)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Magasság")
        sizer_1.Add(label_3, 0, wx.ALL, 5)

        self.magassagText = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_1.Add(self.magassagText, 0, wx.ALL | wx.EXPAND, 5)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Térfogat")
        sizer_1.Add(label_4, 0, wx.ALL, 5)

        self.terfogatText = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_1.Add(self.terfogatText, 0, wx.ALL | wx.EXPAND, 5)

        self.szamolButton = wx.Button(self.panel_1, wx.ID_ANY, u"Számol")
        sizer_1.Add(self.szamolButton, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.szamolButtonClick, self.szamolButton)
        # end wxGlade

    def szamolButtonClick(self, event):  # wxGlade: MainFrame.<event_handler>
        sugarStr = self.sugarText.GetValue()
        magassagStr = self.magassagText.GetValue()
        
        sugar = int(sugarStr)
        magassag = int(magassagStr)
        
        terfogat = 1/3. * math.pow(sugar, 2) * math.pi * magassag
        self.terfogatText.SetValue(str(terfogat))
        event.Skip()

# end of class MainFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
