#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Wed Mar  3 19:12:18 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((412, 373))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.main_sizer = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Gyakos", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.main_sizer.Add(label_1, 0, wx.ALL | wx.EXPAND, 6)

        panel_sizer = wx.BoxSizer(wx.VERTICAL)
        self.main_sizer.Add(panel_sizer, 1, wx.EXPAND, 0)

        self.dolgozo_panel = wx.Panel(self.panel_1, wx.ID_ANY)
        panel_sizer.Add(self.dolgozo_panel, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        label_2 = wx.StaticText(self.dolgozo_panel, wx.ID_ANY, u"Új dolgozó", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_3.Add(label_2, 0, wx.ALL | wx.EXPAND, 6)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_4, 1, wx.ALL | wx.EXPAND, 0)

        label_3 = wx.StaticText(self.dolgozo_panel, wx.ID_ANY, u"Név", style=wx.ALIGN_RIGHT)
        sizer_4.Add(label_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.nev_text_ctrl = wx.TextCtrl(self.dolgozo_panel, wx.ID_ANY, "")
        sizer_4.Add(self.nev_text_ctrl, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.dolgozo_panel, wx.ID_ANY, u"Település", style=wx.ALIGN_RIGHT)
        sizer_5.Add(label_4, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.telepules_text_ctrl = wx.TextCtrl(self.dolgozo_panel, wx.ID_ANY, "")
        sizer_5.Add(self.telepules_text_ctrl, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.dolgozo_panel, wx.ID_ANY, u"Fizetés", style=wx.ALIGN_RIGHT)
        sizer_6.Add(label_5, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.fizetes_text_ctrl = wx.TextCtrl(self.dolgozo_panel, wx.ID_ANY, "")
        sizer_6.Add(self.fizetes_text_ctrl, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.dolgozo_panel, wx.ID_ANY, u"Beosztás", style=wx.ALIGN_RIGHT)
        sizer_7.Add(label_6, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.beosztas_text_ctrl = wx.TextCtrl(self.dolgozo_panel, wx.ID_ANY, "")
        sizer_7.Add(self.beosztas_text_ctrl, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.projekt_panel = wx.Panel(self.panel_1, wx.ID_ANY)
        self.projekt_panel.Hide()
        panel_sizer.Add(self.projekt_panel, 1, wx.EXPAND, 0)

        sizer_8 = wx.BoxSizer(wx.VERTICAL)

        label_7 = wx.StaticText(self.projekt_panel, wx.ID_ANY, u"Új projekt", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_8.Add(label_7, 0, wx.ALL | wx.EXPAND, 6)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_9, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.projekt_panel, wx.ID_ANY, u"Név", style=wx.ALIGN_RIGHT)
        sizer_9.Add(label_8, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.pnev_text_ctrl = wx.TextCtrl(self.projekt_panel, wx.ID_ANY, "")
        sizer_9.Add(self.pnev_text_ctrl, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_10, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.projekt_panel, wx.ID_ANY, u"Leírás", style=wx.ALIGN_RIGHT)
        sizer_10.Add(label_9, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.pleiras_text_ctrl = wx.TextCtrl(self.projekt_panel, wx.ID_ANY, "")
        sizer_10.Add(self.pleiras_text_ctrl, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        button_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.main_sizer.Add(button_sizer, 0, wx.ALL | wx.EXPAND, 6)

        self.balranyil_bitmap_button = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("/home/andras/Desktop/Polc/Egressy/Orai/esti/esti2020Python/gyakos/images/balranyil.png", wx.BITMAP_TYPE_ANY))
        self.balranyil_bitmap_button.SetSize(self.balranyil_bitmap_button.GetBestSize())
        button_sizer.Add(self.balranyil_bitmap_button, 1, wx.ALL | wx.EXPAND, 6)

        self.mentes_bitmap_button = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("/home/andras/Desktop/Polc/Egressy/Orai/esti/esti2020Python/gyakos/images/ment.png", wx.BITMAP_TYPE_ANY))
        self.mentes_bitmap_button.SetSize(self.mentes_bitmap_button.GetBestSize())
        button_sizer.Add(self.mentes_bitmap_button, 1, wx.ALL | wx.EXPAND, 6)

        self.jobbranyil_bitmap_button = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("/home/andras/Desktop/Polc/Egressy/Orai/esti/esti2020Python/gyakos/images/jobbranyil.png", wx.BITMAP_TYPE_ANY))
        self.jobbranyil_bitmap_button.SetSize(self.jobbranyil_bitmap_button.GetBestSize())
        button_sizer.Add(self.jobbranyil_bitmap_button, 1, wx.ALL | wx.EXPAND, 6)

        self.projekt_panel.SetSizer(sizer_8)

        self.dolgozo_panel.SetSizer(sizer_3)

        self.panel_1.SetSizer(self.main_sizer)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.click_balranyil_button, self.balranyil_bitmap_button)
        self.Bind(wx.EVT_BUTTON, self.click_mentes_button, self.mentes_bitmap_button)
        self.Bind(wx.EVT_BUTTON, self.click_jobbranyil_button, self.jobbranyil_bitmap_button)
        # end wxGlade
        
        self.allapot = 0;

    def click_balranyil_button(self, event):  # wxGlade: MainFrame.<event_handler>
        self.dolgozo_panel.Show()
        self.projekt_panel.Hide()
        self.main_sizer.Layout()
        self.allapot = 0;
        event.Skip()
        
    def click_mentes_button(self, event):  # wxGlade: MainFrame.<event_handler>
        if self.allapot == 0:
            self.ment_dolgozo()
        else:
            self.ment_projekt()
        event.Skip()

    def click_jobbranyil_button(self, event):  # wxGlade: MainFrame.<event_handler>
        self.dolgozo_panel.Hide()
        self.projekt_panel.Show()
        self.main_sizer.Layout()
        self.allapot = 1;
        event.Skip()
    
    def ment_dolgozo(self):
        nev = self.nev_text_ctrl.GetValue()
        telepules = self.telepules_text_ctrl.GetValue()
        fizetes = self.fizetes_text_ctrl.GetValue()
        beosztas = self.beosztas_text_ctrl.GetValue()
        self.nev_text_ctrl.SetValue('')
        self.telepules_text_ctrl.SetValue('')
        self.fizetes_text_ctrl.SetValue('')
        self.beosztas_text_ctrl.SetValue('')        
        fp = open('dolgozok.txt', 'a')
        line = nev + ':' + telepules + ':' + fizetes + ':' + beosztas + '\n'
        fp.write(line)
        fp.close()
        print(nev, telepules, fizetes, beosztas)
    
    def ment_projekt(self):
        pnev = self.pnev_text_ctrl.GetValue()
        pleiras = self.pleiras_text_ctrl.GetValue()
        self.pnev_text_ctrl.SetValue('')
        self.pleiras_text_ctrl.SetValue('')
        fp = open('projektek.txt', 'a')
        line = pnev + ':' + pleiras + '\n'
        fp.write(line)
        fp.close()
        print(pnev, pleiras)
        
        
# end of class MainFrame


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # Content of this block not found. Did you rename this class?
        pass

        

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
