#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Wed Mar 10 20:25:33 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 251))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Dolgozók és projektek összerendelés", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_1.Add(label_1, 0, wx.ALL | wx.EXPAND, 16)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Dolgozók", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_2.Add(label_2, 1, wx.ALIGN_BOTTOM | wx.ALL, 6)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Projektek", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_2.Add(label_3, 1, wx.ALIGN_BOTTOM | wx.ALL, 6)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        self.dolgozok_combo = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_3.Add(self.dolgozok_combo, 1, wx.ALL, 6)

        self.projektek_combo = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_3.Add(self.projektek_combo, 1, wx.ALL, 6)

        self.mentes_button = wx.Button(self.panel_1, wx.ID_ANY, u"Mentés")
        sizer_1.Add(self.mentes_button, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 6)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.click_mentes_button, self.mentes_button)
        # end wxGlade
        self.feltolt()
        

    def click_mentes_button(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'click_mentes_button' not implemented!")
        event.Skip()

    def feltolt(self):
        dolgozok = self.leker_adatok('dolgozok.txt')
        projektek = self.leker_adatok('projektek.txt')
        print(dolgozok)
        print(projektek)
        self.dolgozok_combo.Append(dolgozok)
        self.projektek_combo.Append(projektek)
    
    def leker_adatok(self, filename):
        fp = open(filename, 'r', encoding='utf-8')
        lines = fp.readlines()
        fp.close()
        clear_lines = []
        for line in lines:
            line = line.rstrip()
            clear_lines.append(line)
        return clear_lines

   
# end of class MainFrame

class DolprojApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class DolprojApp

if __name__ == "__main__":
    app = DolprojApp(0)
    app.MainLoop()
