#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Wed Mar 31 17:21:57 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade



class ValamiDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ValamiDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("dialog")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.editor_text = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        sizer_1.Add(self.editor_text, 1, wx.EXPAND, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        # end wxGlade
        


# end of class ValamiDialog
class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.open_button = wx.Button(self.panel_1, wx.ID_ANY, u"Megnyitás")
        sizer_1.Add(self.open_button, 0, wx.EXPAND, 0)

        self.save_button = wx.Button(self.panel_1, wx.ID_ANY, u"Mentés")
        sizer_1.Add(self.save_button, 0, wx.EXPAND, 0)

        self.color_button = wx.Button(self.panel_1, wx.ID_ANY, u"Színválasztás")
        sizer_1.Add(self.color_button, 0, wx.EXPAND, 0)

        self.msg_button = wx.Button(self.panel_1, wx.ID_ANY, u"Üzenet")
        sizer_1.Add(self.msg_button, 0, wx.EXPAND, 0)

        self.dialog_button = wx.Button(self.panel_1, wx.ID_ANY, u"Dialógus ablak")
        sizer_1.Add(self.dialog_button, 0, wx.EXPAND, 0)

        self.simpla_button = wx.Button(self.panel_1, wx.ID_ANY, u"Szimpla párbeszéd")
        sizer_1.Add(self.simpla_button, 0, wx.EXPAND, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.on_click_open_button, self.open_button)
        self.Bind(wx.EVT_BUTTON, self.on_click_save_button, self.save_button)
        self.Bind(wx.EVT_BUTTON, self.on_click_color_button, self.color_button)
        self.Bind(wx.EVT_BUTTON, self.on_click_msg_button, self.msg_button)
        self.Bind(wx.EVT_BUTTON, self.on_click_dialog_button, self.dialog_button)
        self.Bind(wx.EVT_BUTTON, self.on_click_simpla_button, self.simpla_button)
        # end wxGlade
        

    def on_click_open_button(self, event):  # wxGlade: MyFrame.<event_handler>
        fd = wx.FileDialog(self)
        if fd.ShowModal() == wx.ID_OK:
            utvonal = fd.GetPaths()
            print(utvonal)
            fp = open(utvonal[0], 'r')
            lines = fp.readlines();            
            fp.close()
            print(lines)
        event.Skip()

    def on_click_save_button(self, event):  # wxGlade: MyFrame.<event_handler>
        fd = wx.FileDialog(self, 
            'Hozzáfűzés',
            '/home',
            'adat.txt',
            'TXT (*.txt)|*.txt',
            style=wx.FD_SAVE
            )
        if fd.ShowModal() == wx.ID_OK:
            utvonal = fd.GetPath()
            print(utvonal)
            fp = open(utvonal, 'a')
            fp.write('málna\n')
            fp.close()
        event.Skip()
    def on_click_color_button(self, event):  # wxGlade: MyFrame.<event_handler>
        cd = wx.ColourDialog(self)
        if cd.ShowModal() == wx.ID_OK:
            colourData = cd.GetColourData();
            szin = colourData.GetColour().Get()
            print(szin)
        event.Skip()
    def on_click_msg_button(self, event):  # wxGlade: MyFrame.<event_handler>
        wx.MessageBox('Helló',
            'Első')
        event.Skip()
    def on_click_dialog_button(self, event):  # wxGlade: MyFrame.<event_handler>
        md = wx.MessageDialog(self, 'Üzenet')
        md.ShowModal()
        event.Skip()
    def on_click_simpla_button(self, event):  # wxGlade: MyFrame.<event_handler>
        vd = ValamiDialog(self)
        vd.Show()
        event.Skip()
# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
