#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.0a9 on Wed Dec 16 18:47:44 2020
#

import wx
import sys

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):        
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Duplázó 1.0")
        sizer_1.Add(label_1, 0, wx.ALL, 5)

        self.numberText = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_1.Add(self.numberText, 0, wx.ALL | wx.EXPAND, 10)

        self.doubleBtn = wx.Button(self.panel_1, wx.ID_ANY, "Dupla")
        sizer_1.Add(self.doubleBtn, 2, wx.ALL | wx.EXPAND, 5)

        self.exitBtn = wx.Button(self.panel_1, wx.ID_ANY, u"Kilépés")
        sizer_1.Add(self.exitBtn, 0, wx.ALL, 5)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.doubleBtnClick, self.doubleBtn)
        self.Bind(wx.EVT_BUTTON, self.exitBtnClick, self.exitBtn)
        # end wxGlade
        

    def doubleBtnClick(self, event):  # wxGlade: MainFrame.<event_handler>
        szamStr = self.numberText.GetValue()
        szam = int(szamStr)
        dupla = szam * 2 
        self.numberText.SetValue(str(dupla))
        event.Skip()

    def exitBtnClick(self, event):  # wxGlade: MainFrame.<event_handler>
        sys.exit()
        event.Skip()
# end of class MainFrame

class EgyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class EgyApp

if __name__ == "__main__":
    app = EgyApp(0)
    app.MainLoop()
